# Generated by Django 4.2 on 2023-04-09 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_ajout']},
        ),
        migrations.AddField(
            model_name='product',
            name='date_ajout',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='store.category'),
            preserve_default=False,
        ),
    ]
