# Generated by Django 4.2 on 2023-04-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_cart_orders_cart_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='orders',
            field=models.ManyToManyField(blank=True, to='store.order'),
        ),
    ]
