# Generated by Django 4.2 on 2023-04-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_cart_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_command',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='date_command',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
