# Generated by Django 4.2 on 2023-04-16 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0013_remove_cart_date_ordered_remove_cart_ordered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_command', models.IntegerField(default=0)),
                ('date_command', models.DateTimeField(blank=True, null=True)),
                ('Cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
