# Generated by Django 4.2 on 2023-04-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_cart_orders_cart_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='address',
            field=models.CharField(default='non renseignée', max_length=200),
        ),
        migrations.AddField(
            model_name='command',
            name='email',
            field=models.EmailField(default='non renseignée', max_length=254),
        ),
        migrations.AddField(
            model_name='command',
            name='pays',
            field=models.CharField(default='Tunisie', max_length=128),
        ),
        migrations.AddField(
            model_name='command',
            name='ville',
            field=models.CharField(default='non renseignée', max_length=128),
        ),
        migrations.AddField(
            model_name='command',
            name='zip',
            field=models.CharField(default='non renseignée', max_length=128),
        ),
        migrations.AlterField(
            model_name='command',
            name='date_command',
            field=models.DateTimeField(auto_now=True, default=''),
            preserve_default=False,
        ),
    ]
