# Generated by Django 4.2 on 2023-04-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_date_ordered_command_date_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_command',
        ),
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
