# Generated by Django 4.2 on 2023-04-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_order_date_command_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='date_command',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
