# Generated by Django 4.2 on 2023-04-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_command_date_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='date_command',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
