# Generated by Django 4.2 on 2023-04-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_command_date_command_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='command',
            name='ville',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='command',
            name='zip',
            field=models.CharField(default='', max_length=128),
        ),
    ]
