# Generated by Django 4.2 on 2023-04-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_command_address_alter_command_ville_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='command',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='command',
            name='pays',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='command',
            name='ville',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='command',
            name='zip',
            field=models.CharField(max_length=128),
        ),
    ]
