# Generated by Django 4.2 on 2023-04-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_command_address_command_email_command_pays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
