# Generated by Django 4.2 on 2023-04-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_command_address_remove_command_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='Address',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='pays',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='ville',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='zip',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
