# Generated by Django 4.2 on 2023-04-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_command_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='command',
            name='email',
        ),
        migrations.RemoveField(
            model_name='command',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='command',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='command',
            name='zip',
        ),
    ]
