# Generated by Django 4.2 on 2023-04-19 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_remove_command_address_remove_command_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='Cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.cart'),
        ),
    ]
