# Generated by Django 4.2 on 2023-04-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_article_command_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
    ]
