# Generated by Django 4.2 on 2023-04-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_command_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='Cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
        ),
        migrations.AlterField(
            model_name='command',
            name='Total_command',
            field=models.IntegerField(default=1),
        ),
    ]
