# Generated by Django 4.2 on 2023-04-20 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_alter_command_cart_alter_command_total_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_Article',
        ),
        migrations.RemoveField(
            model_name='command',
            name='Articles',
        ),
        migrations.AddField(
            model_name='article',
            name='Command',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.command'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='command',
            name='Total_command',
            field=models.IntegerField(default=0),
        ),
    ]
