# Generated by Django 4.2 on 2023-04-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_remove_article_date_article_remove_command_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Nbre_Article',
            field=models.IntegerField(default=0),
        ),
    ]
