# Generated by Django 4.2 on 2023-04-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_article_nbre_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Nbre_Article',
        ),
        migrations.AddField(
            model_name='command',
            name='Nbre_Article',
            field=models.IntegerField(default=0),
        ),
    ]
