# Generated by Django 4.2 on 2023-05-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_publicite'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicite',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
