# Generated by Django 4.2 on 2023-05-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_publicite_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='Address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='pays',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='zip',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
